name: Build Figma Design Token
on:
  push:
    branches: ["main"]
  #   pull_request:
  #     branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: latest
      - run: npm ci
      - run: rm -rf /platform_tokens
      - run: npm run build
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update Design Tokens
          commit_user_name: Design System Bot
